version: "3"

services:
  app:
    build: .
    container_name: go-api
    command: "sh -c 'sqlite3 database.sqlite < structure.sql && go run main.go'"
    volumes:
      - .:/go/src/
    ports:
      - "8000:8000"
