CREATE TABLE IF NOT EXISTS "accounts" (
	"id"	INTEGER NOT NULL UNIQUE,
	"account_number"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "transfer" (
	"id"	INTEGER NOT NULL UNIQUE,
	"from"	TEXT NOT NULL,
	"to"	TEXT NOT NULL,
	"amount"	NUMERIC NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
